name: Karate API Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Maven Tests
        run: mvn clean test

      - name: Upload Test Reports
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: karate-test-reports
          path: target/surefire-reports/